#!/bin/bash

# Stop all processes in screen named "chipi" and "auto_miner" with wiping
screen -ls | grep -E '\<chipi\>|\<auto_miner\>' | cut -d. -f1 | awk '{print $1}' | xargs -I {} screen -X -S {} quit -wipe

# Display message: Stopping processes chipi and auto_miner
echo "Stopping processes chipi and auto_miner"

# Wait for 3 seconds
sleep 3

# Change to user directory
cd /home/user/

# Display message: Entering user directory
echo "Entering user directory"

# Wait for 3 seconds
sleep 3

# Run auto_chipi.sh script in a new screen session named "auto_miner"
screen -dmS auto_miner ./auto_chipi.sh

# Display message: auto_chipi.sh script started in a new screen session
echo "auto_chipi.sh script started in a new screen session"
